### ISSUE TITLE
This doesn't work with Tailwind 2

### ISSUE THREAD

**Issue by Ghirigoro** [chrisdhanaraj/test-svelte-tailwind#4]
Building this with Tailwind 2.0.1 results in the following error:

[!] (plugin svelte) TypeError: Cannot read property 'length' of undefined
src/App.svelte

Removing the style tag in App.svelte fixes the error (but obviously has downsides ;)

**Comment by dimfeld** [comment]
Update your Svelte version to at least 3.30.1 to avoid that error.

**Comment by Ghirigoro** [comment]
Thanks! I've stopped using Svelte on the project so I can't confirm this but I'll mark this as closed.

**Comment by hmaesta** [comment]
Can't make it work too - even in a fresh project -, but the error is different. 

> Error: true is not a PostCSS plugin

Everything is on latest version:
- "rollup": "^2.3.4",
- "svelte": "^3.31.0",
- "tailwindcss": "^2.0.1"
